[package]
name = "LogFormatter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde_json = "1.0.134"
serde = { version = "1.0.216", features = ["derive"] }
regex = "1.11.1"
